import type { GeoProjector } from "../coordinates/projector.ts";
import { ringArea, type BuildingFeature, type LandAreaFeature, type Polygon2D, type RoadClass, type RoadFeature, type Vec2, type WaterFeature, type WorldRegion, type WorldWarning } from "../../world/model/types.ts";
import { clipPolygonToBounds, clipPolylineToBounds } from "../../world/model/clip.ts";

export interface RawOsmNode { readonly type: "node"; readonly id: number; readonly lat: number; readonly lon: number; readonly tags?: Record<string, string>; }
export interface RawOsmWay { readonly type: "way"; readonly id: number; readonly nodes: readonly number[]; readonly tags?: Record<string, string>; }
export interface RawOsmRelation { readonly type: "relation"; readonly id: number; readonly members: readonly { readonly type: string; readonly ref: number; readonly role: string }[]; readonly tags?: Record<string, string>; }
export interface RawOsm { readonly elements: readonly (RawOsmNode | RawOsmWay | RawOsmRelation)[]; }
const roadClasses: Record<string, RoadClass> = { motorway: "motorway", trunk: "trunk", primary: "primary", secondary: "secondary", tertiary: "tertiary", residential: "residential", living_street: "residential", service: "service", pedestrian: "pedestrian", footway: "path", path: "path", cycleway: "path" };
const buildingTypes: Record<string, BuildingFeature["buildingType"]> = { apartments: "residential", house: "residential", detached: "residential", residential: "residential", retail: "commercial", commercial: "commercial", industrial: "industrial", warehouse: "industrial", civic: "civic", public: "civic", church: "religious", cathedral: "religious", chapel: "religious", mosque: "religious", synagogue: "religious", temple: "religious", garage: "garage", garages: "garage", shed: "shed", roof: "roof", mixed_use: "mixed" };
function tagsOf(tags: Record<string, string> | undefined): Readonly<Record<string, string>> { return tags ?? {}; }
function parseMeasure(raw: string | undefined): number | undefined { if (!raw) return undefined; const match = raw.trim().match(/^([0-9]+(?:\.[0-9]+)?)\s*(m|ft)?$/i); if (!match) return undefined; const value = Number(match[1]) * (match[2]?.toLowerCase() === "ft" ? 0.3048 : 1); return Number.isFinite(value) && value > 0 ? value : undefined; }
function parsePositive(raw: string | undefined): number | undefined { const value = raw ? Number(raw.trim()) : NaN; return Number.isFinite(value) && value > 0 ? value : undefined; }
function closedPolygon(points: Vec2[]): Polygon2D | undefined { if (points.length > 1 && points[0].x === points.at(-1)?.x && points[0].y === points.at(-1)?.y) points.pop(); return points.length >= 3 ? { outer: ringArea(points) < 0 ? points.reverse() : points, holes: [] } : undefined; }
function warning(warnings: WorldWarning[], code: string, message: string, featureId?: string): void { warnings.push({ code, message, featureId }); }

export function normalizeOsm(raw: RawOsm, projector: GeoProjector, origin: WorldRegion["geoOrigin"], id = "osm-v0"): WorldRegion {
  const nodes = new Map<number, RawOsmNode>(); const ways: RawOsmWay[] = []; const relations: RawOsmRelation[] = []; const warnings: WorldWarning[] = [];
  for (const element of raw.elements.slice(0, 100_000)) { if (element.type === "node") nodes.set(element.id, element); else if (element.type === "way") ways.push(element); else relations.push(element); }
  const buildings: BuildingFeature[] = []; const roads: RoadFeature[] = []; const landAreas: LandAreaFeature[] = []; const waterAreas: WaterFeature[] = []; const trees: WorldRegion["trees"][number][] = []; const barriers: WorldRegion["barriers"][number][] = [];
  const pointsFor = (way: RawOsmWay): Vec2[] | undefined => { const points = way.nodes.map((nodeId) => { const node = nodes.get(nodeId); return node ? projector.project({ latitude: node.lat, longitude: node.lon }) : undefined; }); if (points.some((point) => !point)) { warning(warnings, "missing-node", "way references a missing node", `osm:way:${way.id}`); return undefined; } return points as Vec2[]; };
  for (const way of ways) { const tags = tagsOf(way.tags); const featureId = `osm:way:${way.id}`; const points = pointsFor(way); if (!points) continue; const buildingTag = tags.building; const highway = tags.highway;
    if (buildingTag) { const footprint = closedPolygon([...points]); if (!footprint) { warning(warnings, "invalid-building", "building ring is not a valid polygon", featureId); } else { buildings.push({ id: featureId, kind: "building", footprint, buildingType: tags.historic && !buildingTypes[buildingTag] ? "historic" : (buildingTypes[buildingTag] ?? "unknown"), source: { provider: "openstreetmap", sourceType: "way", sourceId: String(way.id) }, tags, sourceHeightMeters: parseMeasure(tags.height), sourceLevels: parsePositive(tags["building:levels"]), collisionPolicy: buildingTag === "roof" ? "passable" : "solid" }); } }
    if (highway) { const roadClass = roadClasses[highway] ?? "unknown"; const width = parseMeasure(tags.width); const lanes = parsePositive(tags.lanes); const oneWay = tags.oneway === "yes" || tags.oneway === "1" || tags.oneway === "true" ? true : tags.oneway === "no" || tags.oneway === "0" || tags.oneway === "false" ? false : undefined; roads.push({ id: featureId, kind: "road", centerline: { points }, roadClass, widthMeters: width, laneCount: lanes, oneWay, surface: tags.surface, source: { provider: "openstreetmap", sourceType: "way", sourceId: String(way.id) }, tags }); }
    const landClass = tags.leisure === "park" ? "park" : tags.landuse === "grass" ? "grass" : tags.landuse === "forest" || tags.natural === "wood" ? "forest" : tags.landuse === "industrial" ? "industrial" : tags.landuse === "residential" ? "residential" : tags.landuse === "commercial" || tags.landuse === "retail" ? "commercial" : tags.amenity === "parking" ? "parking" : undefined;
    if (landClass) { const area = closedPolygon([...points]); if (area) landAreas.push({ id: featureId, kind: "land", area, landClass, source: { provider: "openstreetmap", sourceType: "way", sourceId: String(way.id) }, tags }); }
    if (tags.natural === "water") { const area = closedPolygon([...points]); if (area) waterAreas.push({ id: featureId, kind: "water", area, waterClass: tags.water, source: { provider: "openstreetmap", sourceType: "way", sourceId: String(way.id) }, tags }); }
  }
  const waysById = new Map(ways.map((way) => [way.id, way]));
  for (const relation of relations) {
    const tags = tagsOf(relation.tags); const buildingTag = tags.building; if (!buildingTag) continue;
    const outerMember = relation.members.find((member) => member.type === "way" && member.role === "outer");
    if (!outerMember) { warning(warnings, "missing-relation-member", "building relation has no outer way", `osm:relation:${relation.id}`); continue; }
    const outerWay = waysById.get(outerMember.ref); const outerPoints = outerWay ? pointsFor(outerWay) : undefined; const outer = outerPoints ? closedPolygon([...outerPoints]) : undefined;
    if (!outer) { warning(warnings, "invalid-multipolygon", "building relation outer ring is invalid", `osm:relation:${relation.id}`); continue; }
    const holes: Vec2[][] = [];
    for (const member of relation.members.filter((candidate) => candidate.type === "way" && candidate.role === "inner")) { const way = waysById.get(member.ref); const points = way ? pointsFor(way) : undefined; const hole = points ? closedPolygon([...points]) : undefined; if (hole) { const holeRing = [...hole.outer]; if (ringArea(holeRing) > 0) holeRing.reverse(); holes.push(holeRing); } else warning(warnings, "invalid-multipolygon-hole", "building relation inner ring is invalid", `osm:relation:${relation.id}`); }
    buildings.push({ id: `osm:relation:${relation.id}`, kind: "building", footprint: { outer: outer.outer, holes }, buildingType: tags.historic && !buildingTypes[buildingTag] ? "historic" : (buildingTypes[buildingTag] ?? "unknown"), source: { provider: "openstreetmap", sourceType: "relation", sourceId: String(relation.id) }, tags, sourceHeightMeters: parseMeasure(tags.height), sourceLevels: parsePositive(tags["building:levels"]), collisionPolicy: buildingTag === "roof" ? "passable" : "solid" });
  }
  for (const node of nodes.values()) { const tags = tagsOf(node.tags); if (tags.natural === "tree") trees.push({ id: `osm:node:${node.id}`, kind: "tree", position: projector.project({ latitude: node.lat, longitude: node.lon }), source: { provider: "openstreetmap", sourceType: "node", sourceId: String(node.id) }, tags }); }
  const bounds = { minX: -300, minY: -300, maxX: 300, maxY: 300 };
  const clippedBuildings = buildings.flatMap((building) => { const footprint = clipPolygonToBounds(building.footprint, bounds); return footprint ? [{ ...building, footprint }] : []; });
  const clippedRoads = roads.flatMap((road) => { const points = clipPolylineToBounds(road.centerline.points, bounds); return points.length >= 2 ? [{ ...road, centerline: { points } }] : []; });
  const clippedLand = landAreas.flatMap((area) => { const polygon = clipPolygonToBounds(area.area, bounds); return polygon ? [{ ...area, area: polygon }] : []; });
  const clippedWater = waterAreas.flatMap((water) => { const area = water.area ? clipPolygonToBounds(water.area, bounds) : undefined; const line = water.line ? clipPolylineToBounds(water.line.points, bounds) : undefined; return area || (line && line.length >= 2) ? [{ ...water, area, line: line ? { points: line } : undefined }] : []; });
  const clippedTrees = trees.filter((tree) => tree.position.x >= bounds.minX && tree.position.x <= bounds.maxX && tree.position.y >= bounds.minY && tree.position.y <= bounds.maxY);
  return { id, geoOrigin: origin, bounds, buildings: clippedBuildings, roads: clippedRoads, landAreas: clippedLand, waterAreas: clippedWater, barriers, trees: clippedTrees, warnings };
}
