import type { GeoProjector } from "../coordinates/projector.ts";
import { ringArea, type BuildingFeature, type LandAreaFeature, type Polygon2D, type RoadClass, type RoadFeature, type Vec2, type WaterFeature, type WorldRegion, type WorldWarning } from "../../world/model/types.ts";

export interface RawOsmNode { readonly type: "node"; readonly id: number; readonly lat: number; readonly lon: number; readonly tags?: Record<string, string>; }
export interface RawOsmWay { readonly type: "way"; readonly id: number; readonly nodes: readonly number[]; readonly tags?: Record<string, string>; }
export interface RawOsmRelation { readonly type: "relation"; readonly id: number; readonly members: readonly { readonly type: string; readonly ref: number; readonly role: string }[]; readonly tags?: Record<string, string>; }
export interface RawOsm { readonly elements: readonly (RawOsmNode | RawOsmWay | RawOsmRelation)[]; }
const roadClasses: Record<string, RoadClass> = { motorway: "motorway", trunk: "trunk", primary: "primary", secondary: "secondary", tertiary: "tertiary", residential: "residential", living_street: "residential", service: "service", pedestrian: "pedestrian", footway: "path", path: "path", cycleway: "path" };
const buildingTypes: Record<string, BuildingFeature["buildingType"]> = { apartments: "residential", house: "residential", detached: "residential", residential: "residential", retail: "commercial", commercial: "commercial", industrial: "industrial", warehouse: "industrial", civic: "civic", public: "civic", church: "religious", cathedral: "religious", chapel: "religious", mosque: "religious", synagogue: "religious", temple: "religious", garage: "garage", garages: "garage", shed: "shed", roof: "roof", mixed_use: "mixed" };
function tagsOf(tags: Record<string, string> | undefined): Readonly<Record<string, string>> { return tags ?? {}; }
function parseMeasure(raw: string | undefined): number | undefined { if (!raw) return undefined; const match = raw.trim().match(/^([0-9]+(?:\.[0-9]+)?)\s*(m|ft)?$/i); if (!match) return undefined; const value = Number(match[1]) * (match[2]?.toLowerCase() === "ft" ? 0.3048 : 1); return Number.isFinite(value) && value > 0 ? value : undefined; }
function parsePositive(raw: string | undefined): number | undefined { const value = raw ? Number(raw.trim()) : NaN; return Number.isFinite(value) && value > 0 ? value : undefined; }
function closedPolygon(points: Vec2[]): Polygon2D | undefined { if (points.length > 1 && points[0].x === points.at(-1)?.x && points[0].y === points.at(-1)?.y) points.pop(); return points.length >= 3 ? { outer: ringArea(points) < 0 ? points.reverse() : points, holes: [] } : undefined; }
function warning(warnings: WorldWarning[], code: string, message: string, featureId?: string): void { warnings.push({ code, message, featureId }); }

export function normalizeOsm(raw: RawOsm, projector: GeoProjector, origin: WorldRegion["geoOrigin"], id = "osm-v0"): WorldRegion {
  const nodes = new Map<number, RawOsmNode>(); const ways: RawOsmWay[] = []; const warnings: WorldWarning[] = [];
  for (const element of raw.elements.slice(0, 100_000)) { if (element.type === "node") nodes.set(element.id, element); else if (element.type === "way") ways.push(element); }
  const buildings: BuildingFeature[] = []; const roads: RoadFeature[] = []; const landAreas: LandAreaFeature[] = []; const waterAreas: WaterFeature[] = []; const trees: WorldRegion["trees"][number][] = []; const barriers: WorldRegion["barriers"][number][] = [];
  const pointsFor = (way: RawOsmWay): Vec2[] | undefined => { const points = way.nodes.map((nodeId) => { const node = nodes.get(nodeId); return node ? projector.project({ latitude: node.lat, longitude: node.lon }) : undefined; }); if (points.some((point) => !point)) { warning(warnings, "missing-node", "way references a missing node", `osm:way:${way.id}`); return undefined; } return points as Vec2[]; };
  for (const way of ways) { const tags = tagsOf(way.tags); const featureId = `osm:way:${way.id}`; const points = pointsFor(way); if (!points) continue; const buildingTag = tags.building; const highway = tags.highway;
    if (buildingTag) { const footprint = closedPolygon([...points]); if (!footprint) { warning(warnings, "invalid-building", "building ring is not a valid polygon", featureId); } else { buildings.push({ id: featureId, kind: "building", footprint, buildingType: tags.historic && !buildingTypes[buildingTag] ? "historic" : (buildingTypes[buildingTag] ?? "unknown"), source: { provider: "openstreetmap", sourceType: "way", sourceId: String(way.id) }, tags, sourceHeightMeters: parseMeasure(tags.height), sourceLevels: parsePositive(tags["building:levels"]), collisionPolicy: buildingTag === "roof" ? "passable" : "solid" }); } }
    if (highway) { const roadClass = roadClasses[highway] ?? "unknown"; const width = parseMeasure(tags.width); const lanes = parsePositive(tags.lanes); const oneWay = tags.oneway === "yes" || tags.oneway === "1" || tags.oneway === "true" ? true : tags.oneway === "no" || tags.oneway === "0" || tags.oneway === "false" ? false : undefined; roads.push({ id: featureId, kind: "road", centerline: { points }, roadClass, widthMeters: width, laneCount: lanes, oneWay, surface: tags.surface, source: { provider: "openstreetmap", sourceType: "way", sourceId: String(way.id) }, tags }); }
    const landClass = tags.leisure === "park" ? "park" : tags.landuse === "grass" ? "grass" : tags.landuse === "forest" || tags.natural === "wood" ? "forest" : tags.landuse === "industrial" ? "industrial" : tags.landuse === "residential" ? "residential" : tags.landuse === "commercial" || tags.landuse === "retail" ? "commercial" : tags.amenity === "parking" ? "parking" : undefined;
    if (landClass) { const area = closedPolygon([...points]); if (area) landAreas.push({ id: featureId, kind: "land", area, landClass, source: { provider: "openstreetmap", sourceType: "way", sourceId: String(way.id) }, tags }); }
    if (tags.natural === "water") { const area = closedPolygon([...points]); if (area) waterAreas.push({ id: featureId, kind: "water", area, waterClass: tags.water, source: { provider: "openstreetmap", sourceType: "way", sourceId: String(way.id) }, tags }); }
  }
  for (const node of nodes.values()) { const tags = tagsOf(node.tags); if (tags.natural === "tree") trees.push({ id: `osm:node:${node.id}`, kind: "tree", position: projector.project({ latitude: node.lat, longitude: node.lon }), source: { provider: "openstreetmap", sourceType: "node", sourceId: String(node.id) }, tags }); }
  return { id, geoOrigin: origin, bounds: { minX: -300, minY: -300, maxX: 300, maxY: 300 }, buildings, roads, landAreas, waterAreas, barriers, trees, warnings };
}
