import { Application, Container, Graphics } from "pixi.js";
import type { CompiledChunkV0 } from "../../world/compiler/compiled.ts";

export interface PixiRenderer { readonly app: Application; render(chunk: CompiledChunkV0): void; updateVehicle(position: { x: number; y: number }, heading: number): void; }
function drawPolygon(graphics: Graphics, points: readonly { x: number; y: number }[], scale: number, height: number, color: number): void { if (points.length < 3) return; graphics.poly(points.map((point) => ({ x: point.x * scale, y: -point.y * scale }))); graphics.fill(color); if (height > 0) graphics.stroke({ color: 0x27232c, width: 1 }); }
const VEHICLE_LENGTH_METERS = 4.2;
const VEHICLE_WIDTH_METERS = 1.8;
const VEHICLE_VISUAL_SCALE = 2.6;

export async function createPixiRenderer(canvas: HTMLCanvasElement): Promise<PixiRenderer> {
  const app = new Application();
  await app.init({ canvas, background: 0x91a477, antialias: true, preference: "webgl", resizeTo: canvas.parentElement ?? window });
  const world = new Container(); app.stage.addChild(world); let vehicle: Graphics | undefined; let worldScale = 1;
  return { app, render(chunk) { world.removeChildren().forEach((child) => child.destroy()); worldScale = Math.min(app.screen.width, app.screen.height) / 360; world.position.set(app.screen.width / 2, app.screen.height / 2); const ground = new Graphics(); chunk.ground.forEach((area) => drawPolygon(ground, area.area.outer, worldScale, 0, area.styleKey.includes("park") ? 0x70915a : 0x8b9d70)); world.addChild(ground); const roads = new Graphics(); chunk.roads.forEach((road) => drawPolygon(roads, road.surface.outer, worldScale, 0, 0x47454a)); world.addChild(roads); const buildings = new Graphics(); for (const building of chunk.buildings) { const depth = Math.min(24, Math.max(3, building.visualHeightMeters * worldScale * 0.6)); const offset = { x: -depth * 0.707, y: depth * 0.707 }; const facade = building.roof.outer.map((point) => ({ x: point.x + offset.x / worldScale, y: point.y + offset.y / worldScale })); drawPolygon(buildings, facade, worldScale, depth, 0x806c61); drawPolygon(buildings, building.roof.outer, worldScale, 0, building.styleKey.includes("historic") ? 0xa86f5d : 0xb18d77); } world.addChild(buildings); const length = VEHICLE_LENGTH_METERS * worldScale * VEHICLE_VISUAL_SCALE; const width = VEHICLE_WIDTH_METERS * worldScale * VEHICLE_VISUAL_SCALE; vehicle = new Graphics(); vehicle.roundRect(-length / 2, -width / 2, length, width, width * 0.2); vehicle.fill(0xd1495b); vehicle.moveTo(length / 2, 0); vehicle.lineTo(length / 2 - width * 0.35, -width * 0.35); vehicle.lineTo(length / 2 - width * 0.35, width * 0.35); vehicle.closePath(); vehicle.fill(0xf6bd60); vehicle.stroke({ color: 0x8c2636, width: Math.max(0.5, worldScale * 0.6) }); world.addChild(vehicle); }, updateVehicle(position, heading) { if (!vehicle) return; world.position.set(app.screen.width / 2 - position.x * worldScale, app.screen.height / 2 + position.y * worldScale); vehicle.position.set(position.x * worldScale, -position.y * worldScale); vehicle.rotation = -heading; } };
}
