import { Application, Container, Graphics } from "pixi.js";
import type { CompiledChunkV0 } from "../../world/compiler/compiled.ts";

export interface PixiRenderer { readonly app: Application; render(chunk: CompiledChunkV0): void; }
function drawPolygon(graphics: Graphics, points: readonly { x: number; y: number }[], scale: number, height: number, color: number): void { if (points.length < 3) return; graphics.poly(points.map((point) => ({ x: point.x * scale, y: -point.y * scale }))); graphics.fill(color); if (height > 0) graphics.stroke({ color: 0x27232c, width: 1 }); }
export async function createPixiRenderer(canvas: HTMLCanvasElement): Promise<PixiRenderer> {
  const app = new Application();
  await app.init({ canvas, background: 0x91a477, antialias: true, preference: "webgl", resizeTo: canvas.parentElement ?? window });
  const world = new Container(); app.stage.addChild(world);
  return { app, render(chunk) { world.removeChildren().forEach((child) => child.destroy()); const scale = Math.min(app.screen.width, app.screen.height) / 720; world.position.set(app.screen.width / 2, app.screen.height / 2); const ground = new Graphics(); chunk.ground.forEach((area) => drawPolygon(ground, area.area.outer, scale, 0, area.styleKey.includes("park") ? 0x70915a : 0x8b9d70)); world.addChild(ground); const roads = new Graphics(); chunk.roads.forEach((road) => drawPolygon(roads, road.surface.outer, scale, 0, 0x47454a)); world.addChild(roads); const buildings = new Graphics(); for (const building of chunk.buildings) { const depth = Math.min(24, Math.max(3, building.visualHeightMeters * scale * 0.6)); const offset = { x: -depth * 0.707, y: depth * 0.707 }; const facade = building.roof.outer.map((point) => ({ x: point.x + offset.x / scale, y: point.y + offset.y / scale })); drawPolygon(buildings, facade, scale, depth, 0x806c61); drawPolygon(buildings, building.roof.outer, scale, 0, building.styleKey.includes("historic") ? 0xa86f5d : 0xb18d77); } world.addChild(buildings); const vehicle = new Graphics(); vehicle.roundRect(-8, -14, 16, 28, 3); vehicle.fill(0xd1495b); vehicle.moveTo(0, -14); vehicle.lineTo(0, -20); vehicle.stroke({ color: 0xf6bd60, width: 2 }); world.addChild(vehicle); } };
}
